### PR TITLE
Update albedo.csv

### PR DESCRIPTION
**Pull request by IsabelSmith1998**
The article looks at monthly trends and averages across a 6 year period for a grass land region.

### CODE REVIEW

**Comment by sunt05** [comment]
Please check your submitted value: an albedo of 1 is very abnormal. Or, is it some typo?

**Comment by IsabelSmith1998** [comment]
Hi,

Sorry that was a mistake I made, the albedo was actually 0.45. I have fixed it on Github now, just waiting for your approval.

Thanks,

Isabel
________________________________

**Comment by sunt05** [comment]
Hi Isabel,
Have you submitted your change? Is that a Pull Request?
Sorry I cannot see it at my side yet.

Ting

**Comment by sunt05** [comment]
That's weird: if you had submitted your changes as PR, you should see it under the PR tab:
image
which now shows no PR is awaiting my review.
Can you double-check to make sure your PR would appear there?

**Pull request merged**
